UPDATE layaway_agreement
SET
  total_of_payments = $2,
  status = $3,
  number_sold = $4,
  item_status = $5,
  last_updated_at = NOW(),
  last_updated_user_id = $6,
  updated_at = NOW()
WHERE id = $1
RETURNING 
  id,
  ticketnum,
  clerk_user_id,
  date_in,
  last_updated_at,
  amount,
  tax_sales,
  state_tax,
  returned_amt,
  customer_id,
  note,
  status,
  default_date,
  total_of_payments,
  period,
  extra_note,
  gun_proc_fee,
  last_updated_user_id,
  inventory_number,
  number_sold,
  item_amount,
  description,
  tax_exempt,
  return_sold,
  item_status,
  county_tax_exempt,
  item_last_updated_user_id,
  items_id,
  created_at,
  updated_at;
