INSERT INTO layaway_agreement (
  id,
  ticketnum,
  clerk_user_id,
  date_in,
  last_updated_at,
  amount,
  tax_sales,
  state_tax,
  returned_amt,
  customer_id,
  note,
  status,
  default_date,
  total_of_payments,
  period,
  extra_note,
  gun_proc_fee,
  last_updated_user_id,
  inventory_number,
  number_sold,
  item_amount,
  description,
  tax_exempt,
  return_sold,
  item_status,
  county_tax_exempt,
  item_last_updated_user_id,
  items_id,
  created_at,
  updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 
  $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, 
  $21, $22, $23, $24, $25, $26, $27, $28, $29, $30
) RETURNING *;
