SELECT 
    id,
    inventory_item_id,
    manufacturer,
    model,
    serial,
    caliber,
    action,
    condition,
    guntype,
    importer,
    buyer_amount,
    buyer_date,
    buyer_first_name,
    buyer_middle_name,
    buyer_last_name,
    buyer_street_address,
    buyer_city,
    buyer_state_us,
    buyer_zip_code,
    buyer_id_type,
    buyer_id_number,
    sold_date,
    sold_first_name,
    sold_middle_name,
    sold_last_name,
    sold_street_address,
    sold_city,
    sold_state_us,
    sold_zip_code,
    sold_amount,
    sold_id_type,
    sold_id_number,
    nicstn,
    transaction_num,
    created_at,
    updated_at
FROM gunlog
WHERE inventory_item_id = $1
ORDER BY created_at DESC
LIMIT 1;
