SELECT
  st.id,
  st.legacy_acct_pk,
  st.legacy_acct_id,
  st.legacy_ticketnum,
  st.legacy_cus_fk,
  st.legacy_usr_fk,
  st.customer_id,
  st.clerk_user_id,
  st.type_id,
  st.occurred_at,
  st.amount,
  st.tax_sales,
  st.tax_exempt_used,
  st.state_tax,
  st.tender_change,
  st.override_amount,
  st.gun_proc_fee,
  st.note,
  st.created_at,
  st.updated_at,
  st.pawn_ticket_id,
  st.interest_amount,
  st.principal_amount,
  st.fees_amount,
  stt.id AS type_detail_id,
  stt.code AS type_code,
  stt.legacy_code AS type_legacy_code,
  stt.name AS type_name,
  stt.cash_dir AS type_cash_dir,
  stt.active AS type_active,
  sti.id AS item_id,
  sti.store_transaction_id AS item_store_transaction_id,
  sti.sequence AS item_sequence,
  sti.inventory_item_id AS item_inventory_item_id,
  sti.description AS item_description,
  sti.quantity AS item_quantity,
  sti.line_amount AS item_line_amount,
  sti.line_cost AS item_line_cost,
  sti.tax_exempt AS item_tax_exempt,
  sti.county_tax_exempt AS item_county_tax_exempt,
  sti.returned AS item_returned,
  sti.status AS item_status,
  sti.legacy_sitem_pk AS item_legacy_sitem_pk,
  sti.legacy_items_pk AS item_legacy_items_pk,
  sti.legacy_items_guid AS item_legacy_items_guid,
  sti.legacy_invnum AS item_legacy_invnum,
  sti.legacy_vendor_pk AS item_legacy_vendor_pk,
  sti.legacy_from_customer_pk AS item_legacy_from_customer_pk,
  sti.legacy_cflag AS item_legacy_cflag,
  sti.legacy_sit_id AS item_legacy_sit_id,
  sti.legacy_sales_loc AS item_legacy_sales_loc,
  sti.legacy_last_updated_usr AS item_legacy_last_updated_usr,
  sti.created_at AS item_created_at,
  customer.id AS customer_id,
  customer.old_customer_pk AS customer_old_customer_pk,
  customer.old_customer_id AS customer_old_customer_id,
  customer.first_name AS customer_first_name,
  customer.middle_name AS customer_middle_name,
  customer.last_name AS customer_last_name,
  customer.street_address AS customer_street_address,
  customer.suite_number AS customer_suite_number,
  customer.city AS customer_city,
  customer.state_us AS customer_state_us,
  customer.zip_code AS customer_zip_code,
  customer.phone_number AS customer_phone_number,
  customer.height AS customer_height,
  customer.weight AS customer_weight,
  customer.hair_color AS customer_hair_color,
  customer.eye_color AS customer_eye_color,
  customer.race AS customer_race,
  customer.sex AS customer_sex,
  customer.marks AS customer_marks,
  customer.date_of_birth AS customer_date_of_birth,
  customer.birth_city AS customer_birth_city,
  customer.birth_state AS customer_birth_state,
  customer.birth_country AS customer_birth_country,
  customer.id_type AS customer_id_type,
  customer.id_number AS customer_id_number,
  customer.id_expiration AS customer_id_expiration,
  customer.id_issue_date AS customer_id_issue_date,
  customer.ss_number AS customer_ss_number,
  customer.id_address AS customer_id_address,
  customer.id_suite_number AS customer_id_suite_number,
  customer.id_city AS customer_id_city,
  customer.id_state AS customer_id_state,
  customer.id_zip AS customer_id_zip,
  customer.employer_name AS customer_employer_name,
  customer.employer_address AS customer_employer_address,
  customer.employer_suite_number AS customer_employer_suite_number,
  customer.employer_city AS customer_employer_city,
  customer.employer_state AS customer_employer_state,
  customer.employer_zip AS customer_employer_zip,
  customer.employer_phone_number AS customer_employer_phone_number,
  customer.description AS customer_description,
  customer.ffl_number AS customer_ffl_number,
  customer.locked AS customer_locked,
  customer.tax_id AS customer_tax_id,
  customer.cell_phone AS customer_cell_phone,
  customer.email AS customer_email,
  customer.entered_at AS customer_entered_at,
  customer.military AS customer_military,
  customer.ffl_expire_date AS customer_ffl_expire_date,
  customer.tax_exempt AS customer_tax_exempt,
  customer.tax_exempt_certificate AS customer_tax_exempt_certificate,
  customer.created_at AS customer_created_at,
  customer.updated_at AS customer_updated_at
FROM store_transaction st
JOIN store_transaction_type stt ON stt.id = st.type_id
INNER JOIN customer ON customer.id = st.customer_id
LEFT JOIN store_transaction_item sti ON sti.store_transaction_id = st.id
WHERE stt.code = 'SS'
  AND st.occurred_at >= $1
  AND st.occurred_at <= $2
ORDER BY st.occurred_at DESC;
